### PR TITLE
Merge for Ryerson :')

### PR DESCRIPTION
**Pull request by ImJeremyy**
Screw the corona virus :(

### CODE REVIEW

**Comment by ImJeremyy** [comment]
Wow we just won Ryerson guys!

**Comment by scott-work** [comment]
Rip season

**Review by scott-work — APPROVED** [review]

**Comment by ImJeremyy** [comment]
> Rip season

saaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad

**Comment by ImJeremyy** [comment]
`if (Ryerson.hasWon == true) {
    celebrate();
}`

**Comment by ImJeremyy** [comment]
`System.out.println("We are big sad");`

**Pull request merged**
